### ISSUE TITLE
No longer works with solcjs 0.6.*

### ISSUE THREAD

**Issue by MicahZoltu** [beaugunderson/vscode-solidity-extended#10]
The exported functions have changed so I now get
> solc error: TypeError: solc.compileStandardWrapper is not a function
In the output window for Solidity Language Server.

I _think_ the fix is as easy as changing that to `solc.compile`.

**Comment by roughpandaz** [comment]
@MicahZoltu Where in VSCode do you change this setting?

**Comment by MicahZoltu** [comment]
The proposed fix is something that needs to happen in the extension, not in VSCode.

**Comment by birkasecorba** [comment]
Having the same issue on remote code-server. When I save any .sol file, the output pops out any displays this error.

**Comment by beaugunderson** [comment]
happy to merge any fix or transfer to someone willing to take
maintainership (Micah?)

**Comment by MicahZoltu** [comment]
Unfortunately I don't have the time to maintain this.  😢

**Comment by roughpandaz** [comment]
@beaugunderson @MicahZoltu, I would be happy to take a look at this issue, if you can: 
- point me to the file
- give me a note on what needs to be updated.

**Comment by MicahZoltu** [comment]
I'm not sure where `solc.compileStandardWrapper` is called in this codebase, but if you can find that try changing it to `solc.compile` and seeing if that fixes the issue.

**Comment by elkattan** [comment]
Hey @RongxinZhang @MicahZoltu, according to the error output, the call occurs in `$HOME/.vscode/extensions/beaugunderson.solidity-extended-3.0.2/out/src/server.js:92`.

But following fixing that as @MicahZoltu suggested a new Assertion error `solc error: AssertionError [ERR_ASSERTION]: Invalid callback object specified.`, it's expecting an object but a function is passed

**Comment by MicahZoltu** [comment]
The signature of the function changed along with its name a while back.  Check out https://github.com/ethereum/solc-js#high-level-api for details on this.  `compile(JSON.stringify(input), { import: (importPath) => { ... } })` or something along those lines should do the trick.

**Comment by lichaks** [comment]
> https://github.com/ethereum/solc-js#high-level-api

Did u fix it? I have the same problem in vscode

**Comment by corporateenvoys** [comment]
i think edit pragma statement can solve this issue..

**Comment by rameez-dgc** [comment]
I am having the same issue on vscode. Anyone found the solution ?

**Comment by birkasecorba** [comment]
I've downloaded https://open-vsx.org/extension/juanblanco/solidity from open vsx registry and installed it manually. Solved all the issues @rameez-dgc

**Comment by lucasmshepherd** [comment]
Ah just needed to remove this extension.  This error was showing up on simple saves so annoying.
